### ISSUE TITLE
Add Company to Employee

### ISSUE THREAD

**Issue by ldco2016** [ldco2016/overtime-app#3]
Add an attribute of the company to the employee like so:

`rails g migration add_params_to_users ssn:integer company:string`

There are a few companies inside of this parent company, so there is no need to create a company model and say an employee `belongs_to` the company. Eventually, I will create a helper method that stores a list of the companies in the code and that will be all that is needed.

Resulting migration should look like so:

```
class AddParamsToUsers < ActiveRecord::Migration[5.0]
  def change
    add_column :users, :ssn, :integer
    add_column :users, :company, :string
  end
end
```

`user_spec.rb` test should look like so:

```
it 'requires the ssn attr' do
      @user.ssn = nil
      expect(@user).to_not be_valid
    end

    it 'requires a company' do
      @user.company = nil
      expect(@user).to_not be_valid
    end
```

Should result in the following 2 failures:

```
Failures:

  1) User validations requires the ssn attr
     Failure/Error: expect(@user).to_not be_valid
       expected #<User id: 53, email: "test53@example.com", first_name: "Ed", last_name: "Snowden", created_at: "2018-07-02 16:12:31", updated_at: "2018-07-02 16:12:31", phone: "8565551212", ssn: nil, company: nil> not to be valid
     # ./spec/models/user_spec.rb:41:in `block (3 levels) in <top (required)>'

  2) User validations requires a company
     Failure/Error: expect(@user).to_not be_valid
       expected #<User id: 54, email: "test54@example.com", first_name: "Ed", last_name: "Snowden", created_at: "2018-07-02 16:12:31", updated_at: "2018-07-02 16:12:31", phone: "8565551212", ssn: nil, company: nil> not to be valid
     # ./spec/models/user_spec.rb:46:in `block (3 levels) in <top (required)>'
```

To correct this, must go to `user.rb`:

```
class User < ActiveRecord::Base
  has_many :posts
  has_many :audit_logs

  has_many :hands_associations, class_name: 'Hand'
  has_many :hands, through: :hands_associations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name, :phone

  PHONE_REGEX = /\A[0-9]*\z/

  validates_format_of :phone, with: PHONE_REGEX

  validates :phone, length: {is: 10}

  def full_name
    last_name.upcase + ", " + first_name.upcase
  end
end
```

and refactor code like so:

```
class User < ActiveRecord::Base
  has_many :posts
  has_many :audit_logs

  has_many :hands_associations, class_name: 'Hand'
  has_many :hands, through: :hands_associations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name, :phone, :ssn, :company

  PHONE_REGEX = /\A[0-9]*\z/

  validates_format_of :phone, with: PHONE_REGEX

  validates :phone, length: {is: 10}

  def full_name
    last_name.upcase + ", " + first_name.upcase
  end
end
```

**Comment by ldco2016** [comment]
Running `rspec` found that refactor worked, but we got 40 failures because anywhere we have a user creation, now we need to add the two elements of `:ssn` and `:company`.

To fix this issue, it is recommended to start off in user factories of `spec/factories/users.rb`:

```
FactoryBot.define do
  sequence :email do |n|
    "test#{n}@example.com"
  end

  factory :user do
    first_name 'Ed'
    last_name 'Snowden'
    email {generate :email}
    password 'ayodele1'
    password_confirmation 'ayodele1'
    phone "8565551212"
    ssn 1234
    company "ABC Company"
  end

  factory :admin_user, class: "AdminUser" do
    first_name 'Admin'
    last_name 'User'
    email {generate :email}
    password 'ayodele1'
    password_confirmation 'ayodele1'
    phone "8565551212"
    ssn 1234
    company "ABC Company"
  end

  factory :non_authorized_user, class: "User" do
    first_name 'Non'
    last_name 'Authorized'
    email {generate :email}
    password "password"
    password_confirmation "password"
    phone "8565551212"
    ssn 1234
    company "ABC Company"
  end
end
```

For this fix to work, a validation must be added that says SSN must be an integer and has to only be four characters long. This will not fix all the tests, but it should fix a number of them.

**Comment by ldco2016** [comment]
Correction, fix actually fixed all errors, will not need to create any users separately.
