### ISSUE TITLE
Last four of SSN

### ISSUE THREAD

**Issue by ldco2016** [ldco2016/overtime-app#6]
Very important because we are dealing with something that is secure so I will have to implement a way to encrypt data.

`rails g migration add_params_to_users ssn:integer company:string`

**Comment by ldco2016** [comment]
Now we must go to `seeds.rb` file and create an SSN for the employee and a company like so:

```
@employee = Employee.create(email: "test@test.com", password: "ayodele1",
                      password_confirmation: "ayodele1",
                      first_name: "Edward", last_name: "Snowden", phone: "6095053395",
                      ssn: 1234, company: "ABC Company")

puts "1 employee created"

AdminUser.create(email: "admin@test.com", password: "ayodele1",
                  password_confirmation: "ayodele1",
                  first_name: "Admin", last_name: "employee", phone: "6095053395",
                  ssn: 1234, company: "ABC Company")

puts "1 Admin employee created"

AuditLog.create!(user_id: @employee.id, status: 0, start_date: (Date.today - 6.days))
AuditLog.create!(user_id: @employee.id, status: 0, start_date: (Date.today - 13.days))
AuditLog.create!(user_id: @employee.id, status: 0, start_date: (Date.today - 20.days))

puts "3 audit logs have been created"

100.times do |post|
  Post.create!(date: Date.today, rationale: "#{post} rationale content Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                                  user_id: @employee.id, overtime_request: 2.5)
end

puts "100 Posts have been created"
```
This company has around 1,000 employees, so there are plenty of chances of employees having first and last name. So the last 4 of SSN helps determine who is a unique employee in the payroll system. That's the reason for this new feature.

Do not forget to run:

`bundle exec rake db:setup`

in order to update `seeds.rb` file.

To test this implementation in `user_spec.rb`, we add the following:

```
it "requires the ssn attr to only contain integers" do
      @user.ssn = 'mygreatstr'
      expect(@user).to_not be_valid
    end

    it "requires the ssn attr to only have 10 chars" do
      @user.ssn = '12345'
      expect(@user).to_not be_valid
    end
```

This should give us two failures like so:

```
Failures:

  1) User validations requires the ssn attr to only contain integers
     Failure/Error: expect(@user).to_not be_valid
       expected #<User id: 53, email: "test55@example.com", first_name: "Ed", last_name: "Snowden", created_at: "2018-07-02 16:51:54", updated_at: "2018-07-02 16:51:54", phone: "8565551212", ssn: 0, company: "ABC Company"> not to be valid
     # ./spec/models/user_spec.rb:51:in `block (3 levels) in <top (required)>'

  2) User validations requires the ssn attr to only have 10 chars
     Failure/Error: expect(@user).to_not be_valid
       expected #<User id: 54, email: "test56@example.com", first_name: "Ed", last_name: "Snowden", created_at: "2018-07-02 16:51:54", updated_at: "2018-07-02 16:51:54", phone: "8565551212", ssn: 12345, company: "ABC Company"> not to be valid
     # ./spec/models/user_spec.rb:56:in `block (3 levels) in <top (required)>'

Finished in 3.03 seconds (files took 4.05 seconds to load)
44 examples, 2 failures

Failed examples:

rspec ./spec/models/user_spec.rb:49 # User validations requires the ssn attr to only contain integers
rspec ./spec/models/user_spec.rb:54 # User validations requires the ssn attr to only have 10 chars
```

At this point we need to look at our implementation in our `user.rb` file and add the following:

```
class User < ActiveRecord::Base
  has_many :posts
  has_many :audit_logs

  has_many :hands_associations, class_name: 'Hand'
  has_many :hands, through: :hands_associations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name, :phone, :ssn, :company

  PHONE_REGEX = /\A[0-9]*\z/

  validates_format_of :phone, with: PHONE_REGEX

  validates :phone, length: {is: 10}
  validates :ssn, length: {is: 4}
  validates_numericality_of :ssn

  def full_name
    last_name.upcase + ", " + first_name.upcase
  end
end
```

Then run `rspec` again and it should get all of them passing.
